#!/usr/bin/env bash

NEW_HOSTNAME="MrBeam-XXXX"
OLD_HOSTNAME=`hostname`

if [ -n "$1" ]; then
  NEW_HOSTNAME="$1"
else
  PI_SERIAL=`cat /proc/cpuinfo | grep Serial | cut -d" " -f2 | awk '{print toupper($0)}'`
  HASH=`echo $PI_SERIAL | openssl dgst -sha1 | awk '{print toupper($NF)}'`
  if [ -n "$HASH" ]; then
    NEW_HOSTNAME=MrBeam-${HASH:(-4)}
  fi
fi

echo "$NEW_HOSTNAME" > /etc/hostname
sed -i -e "s@$OLD_HOSTNAME@$NEW_HOSTNAME@g" /etc/hosts
