#!/usr/bin/env bash

if [ ! -e '/etc/netconnectd.yaml' ]
then
  exit 1
fi

NEW_APNAME="MrBeam-XXXX"

if [ -n "$1" ]; then
  NEW_APNAME="$1"
else
  PI_SERIAL=`cat /proc/cpuinfo | grep Serial | cut -d" " -f2 | awk '{print toupper($0)}'`
  HASH=`echo $PI_SERIAL | openssl dgst -sha1 | awk '{print toupper($NF)}'`
  if [ -n "$HASH" ]; then
    NEW_APNAME=MrBeam-${HASH:(-4)}
  fi
fi

sed -i "/[[:blank:]]*ssid: .*/c\  ssid: $NEW_APNAME" /etc/netconnectd.yaml
