# Deployment workflow to be used for Jira reporting
name: Deploy alpha to Development

on:
  push:
    branches: ["alpha"]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-dev:
    name: Deploy to Dev environment
    # IMPORTANT: the workflow must have write access to deployments, otherwise the action will fail.
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment-dev
        with:
          token: '${{ github.token }}'
          environment: development

      - name: Update deployment status (success)
        if: ${{ success() }}
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'success'
          deployment-id: ${{ steps.deployment-dev.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: ${{ failure() }}
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'failure'
          deployment-id: ${{ steps.deployment-dev.outputs.deployment_id }}

      - name: Update deployment status (cancelled)
        if: ${{ cancelled() }}
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'cancelled'
          deployment-id: ${{ steps.deployment-dev.outputs.deployment_id }}
